post:
  tags:
    - config
  summary: Open a new session
  description: ''
  operationId: addConfiguration
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Configuration.yaml
    description: The session configuration which is being created.
    required: true
  responses:
    '405':
      description: Invalid input
