# MVP config
nodes:
  ri1:
    description: Research infrastructure 1

    uapi_endpoint: http://localhost:8081 # Optional

    channels: # This node provides (sources) these channels

    - { id: ri1::rtds:f, unit: Hz, rate: 10.0 }
    - { id: ri1::rtds:U, unit: kV, rate: 10.0 }

    transport:
      type: villas

      # All following attributes are specific to the type of transport
      # and not covered by the global config schema.
      villas-node:
        host: localhost
        port: 9001

  ri2:
    description: Research infrastructure 2

    uapi_endpoint: http://localhost:8082 # Optional

    channels: # This node provides (sources) these channels

    - { id: ri2::amp:P, unit: mW, rate: 10.0 }
    - { id: ri2::amp:Q, unit: pu, rate: 10.0 }

    transport:
      type: villas

      # All following attributes are specific to the type of transport
      # and not covered by the global config schema.
      villas-node:
        host: localhost
        port: 9002

connections:
- {from: ri1::rtds:f, to: ri2}
- {from: ri1::rtds:U, to: ri2}
- {from: ri2::amp:P, to: ri1}
- {from: ri2::amp:Q, to: ri1}

ri_adapters:
- type: mvp_adapter

  nodes:
  - ri1
  - ri2
