# Local RI 1 mvp config
nodes:
  uapi_endpoint: http://localhost:8081

  channels: # This node provides (sources) these channels
    incoming:
    - { id: ri2::amp:P}
    - { id: ri2::amp:Q}
    outgoing:
    - { id: ri1::rtds:f, unit: Hz, rate: 10.0, description: "PCC frequency"  }
    - { id: ri1::rtds:U, unit: kV, rate: 10.0, description: "PCC voltage" }

  transport:
    type: villas

    # All following attributes are specific to the type of transport
    # and not covered by the global config schema.
    villas-node:
      api-host: localhost
      api-port: 9001
      node-type: udp

    resolver-result:
      startup: yes
      address-outgoing: "localhost:4445"
      address-incoming: "localhost:4446"
  
ri_adapters: #probably to be moved to local lab configurations
- type: mvp_adapter

  nodes:
  - ri1
  - ri2
