---
get:
  tags:
  - configuration
  summary: Get all configurations
  description: ''
  operationId: getConfigurations
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Configuration.yaml
    description: The session configuration which is being created.
    required: true
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/ConfigurationId.yaml
    '405':
      description: Invalid input

post:
  tags:
  - configuration
  summary: Open a new session
  description: ''
  operationId: addConfiguration
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Configuration.yaml
    description: The session configuration which is being created.
    required: true
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ConfigurationId.yaml
    '405':
      description: Invalid input
