---
openapi: 3.0.1
info:
  title: ERIGrid Universal Data Exchange API
  description: "A common API used by ERIGrid research infrastructures to exchange signals for geographically distributed experiments."
  termsOfService: https://erigrid2.eu/disclaimer/
  contact:
    name: ERIGrid 2.0 consortium
    email: info@erigrid2.eu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0alpha
  x-logo:
    url: https://erigrid2.eu/wp-content/uploads/2020/06/cropped-Logo_ERIGrid2_4C_highRes-01_.png
    backgroundColor: "#ffffff"
    href: https://erigrid2.eu

externalDocs:
  description: Find out more about ERIGrid 2.0
  url: 'https://erigrid2.eu'

servers:
- url: 'https://api.erigrid2.eu/v1'
- url: 'http://api.erigrid2.eu/v1'

tags:
- name: api
  description: API handling

- name: signals
  description: Signal handling

paths:
  /info:
    $ref: paths/info.yaml
  /config:
    $ref: paths/config.yaml
  /signals:
    $ref: paths/signals.yaml
  /signal/{id}':
    $ref: paths/signal@{id}.yaml
