name: Build docs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create public dir
      run: mkdir public
    - name: Copy static assets
      run: cp docs/* public/
    - name: Build middleware API
      run: npx redoc-cli build -t docs/template.html -o public/middleware.html openapi/middleware/openapi.yaml
    - name: Build universal API
      run: npx redoc-cli build -t docs/template.html -o public/universal-api.html openapi/universal-api/openapi.yaml
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        cname: erigrid2.github.io
        force_orphan: true
